spring.application.name=vaadin-demo
vaadin.launch-browser=true
spring.main.allow-bean-definition-overriding=true
server.port=${PORT:8080}
logging.level.org.atmosphere=warn
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode